Feature: Parameter file editing
    In order to generate a parameter file for an ARM resource
    As a reader of a parameter file
    I want parameter file represented as a plain object
    according to either an imported file or constrictor function 

    Scenario: Writing to a Parameter file 
        Given I am writing to a parameter file
            |name                                                        |  properties|
        When I attempt to write to a file
            Then I collect the parameters generated by previous work
            Then I locate the template engine file I am using
            Then I write the new values to the template engine file, per parameter
            Then I select a destination for the written parameter file